wiremock/wiremock-testcontainers-java

.github/workflows/maven.yml
README.md
pom.xml
src/main/java/org/wiremock/integrations/testcontainers/WireMockContainer.java
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerExtensionTest.java
src/test/resources/org/wiremock/integrations/testcontainers/WireMockContainerExtensionTest/json-body-transformer.json

Adds support for using extensions

Introduce support for WireMock extensions

---

pom.xml

**Improvements:**
1. Simplify dependency management thanks to utilization BOM
2. Allow to run Junit4 and Junit5 test together
3. Fix Wrong indentation in pom.xml

Feature/Re-organize Dependencies and enable Juni4 & Junit5 execution togeter

---

.github/workflows/release.yml
jreleaser.yml

As mentioned by @aalmiray in https://twitter.com/aalmiray/status/1648414396278816775, the configuration was broken, and JReleaser actually failed for the previous version. This patch should help

Update the release flow to take the version as a parameter, and pass it to JReleaser

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

As discussed in #13, I am not sure I will proceed with JReleaser or not for now. So let's get the Pipelines to draft release changelog with Release Drafter too

Add Release Drafter to the repository

---

README.md
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerJUnit5Test.java

@oleg-nenashev I have added existing example tests in JUnit 5.
Resolves #8

Add JUnit5 test coverage and documentation

---

pom.xml

Fixing logging error
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
Dependencies Before fix
```log
[INFO] +- org.testcontainers:testcontainers:jar:1.18.0:compile
[INFO] |  +- junit:junit:jar:4.13.2:compile (scope not updated to compile)
[INFO] |  |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.36:compile (scope not updated to compile)
[INFO] \- ch.qos.logback:logback-classic:jar:1.4.7:provided
[INFO]    +- ch.qos.logback:logback-core:jar:1.4.7:provided
[INFO]    \- (org.slf4j:slf4j-api:jar:2.0.4:provided - omitted for conflict with 1.7.36)
```
Dependencies After fix
```log
[INFO] …
```

Fix SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder"

---

.github/workflows/release.yml

Currently we use Release Drafter for changelogs, and we do not need to attach artifacts to the release since we use GitHub Packages. I will disable the code for now, and restore once we start using JReleaser for something else like announcements

Disable JReleaser in the release pipeline

---

src/main/java/org/wiremock/integrations/testcontainers/WireMockContainer.java

default waiting strategy needs to be configured in constructor.
method `configure()`  is being executed right before container starts, so if we set  waiting strategy  here we will override any user specified waiters
```java
public WireMockContainer wiremockServer = new WireMockContainer("2.35.0")
.waitingFor(Wait.defaultWaitStrategy()) // ignored due to bug
.withStartupTimeout(Duration.ofSeconds(11)) // ignored due to bug
```
```java
public WireMockContainer wiremockServer = new WireMockContainer("2.35.0")
.waitingFor(Wait.defaultWaitStrategy()) // developer able to override strategy
.withStartupTimeout(Duration.ofSeconds(11)) // developer able to override timeout
```

Allow to override waiting strategy and waiting time

---

src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerExtensionTest.java
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerExtensionsCombinationTest.java
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerJUnit5Test.java
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerTest.java
src/test/java/org/wiremock/integrations/testcontainers/testsupport/http/TestHttpClient.java

In every test method we have duplicated code block
```java
final HttpClient client = HttpClient.newBuilder().build();
final HttpRequest request = HttpRequest.newBuilder()
.uri(URI.create(wiremockServer.getUrl("/json-body-transformer")))
.timeout(Duration.ofSeconds(10))
.header("Content-Type", "application/json")
.POST(HttpRequest.BodyPublishers.ofString("{\"name\":\"John Doe\"}")).build();
```
This code block and similar once were extracted into testsupport utility class `TestHttpClient`
Result test you can see bellow:
```java
// given
String url = wiremockServer.getUrl("/json-body-transformer");
String body = "{\"name\":\"John Doe\"}";
// when
HttpResponse<String> response = TestHttpClient.newInstance().post(url, body);
// then
assertThat(response.body())
.as("Wrong response body") …
```

Reduce Code duplication in tests and make tests easier to read

---

pom.xml
src/main/java/org/wiremock/integrations/testcontainers/WireMockContainer.java
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerJUnit5Test.java
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerUnitTest.java

Now the container is running by default with the cli arg --disabled. When using the verbose flag, the banner is shown when starting. 
Issue -> https://github.com/wiremock/wiremock-testcontainers-java/issues/31

Disable WireMock banner in the CLI output by default 

---

pom.xml
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerExtensionsWebhookTest.java
src/test/java/org/wiremock/integrations/testcontainers/testsupport/http/TestHttpServer.java
src/test/resources/org/wiremock/integrations/testcontainers/WireMockContainerExtensionsWebhookTest/webhook-callback-template.json

When we work with Webhook callbacks, Testcontainers(Docker) brings additional complexity related to networking, because wiremock that inside docker needs to make request to host machine. This requires additional configuration 
That is why i decided to add Tests that verify it and could be used as an example in documentation (in future) 
https://www.testcontainers.org/features/networking/
N/A

Webhook test and Testcontainers networking

---

pom.xml
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerExtensionTest.java
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerExtensionsCombinationTest.java
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerExtensionsWebhookTest.java
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerJUnit5Test.java
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerTest.java
src/test/java/org/wiremock/integrations/testcontainers/testsupport/http/TestHttpClient.java
src/test/java/org/wiremock/integrations/testcontainers/testsupport/http/TestHttpServer.java

Downgrade to Java 1.8 to ensure compatibility.
https://github.com/wiremock/wiremock-testcontainers-java/issues/12

Java 1.8 compatibility

---

README.md

Just a minor PR, mostly to test Release Drafter

Reference main contributor guide, update badges

---

README.md

Documents using the modulke with GitHub Packages and JitPack, until #56 is completed

Document using GitPack or GitHub Packages as a source

---

src/main/java/org/wiremock/integrations/testcontainers/WireMockContainer.java
src/main/java/org/wiremock/integrations/testcontainers/WireMockPlugin.java
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerExtensionTest.java
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerExtensionsCombinationTest.java
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerExtensionsWebhookTest.java

Introduce Plugin API and refactor extension management

---

src/main/java/org/wiremock/integrations/testcontainers/WireMockContainer.java
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerWithWireMockVersionThreeTest.java

As part of this PR, it has added /health endpoint as waiting strategy for docker images with minimum version 3.0.0-1. 
Resolves => https://github.com/wiremock/wiremock-testcontainers-java/issues/28

Add /health endpoint in waiting strategy

---

.github/workflows/release.yml
pom.xml

For #56 , most likely does not work but we will give it a try

Add Maven Central release configuration

---

README.md

Release the module to Maven Central

---

src/main/java/org/wiremock/integrations/testcontainers/WireMockContainer.java
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerJunit4Test.java
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerTest.java

…r configuration
Currently it is impossible to configure SSL, rather than go through all the hoops to add proper configuration for SSL I've applied this hotfix. By using addExposedPort we do not override the user configuration. Currently if I was to do the following:
```
WireMockContainer wiremockServer = new WireMockContainer("wiremock/wiremock:2.35.0").withExposedPorts(8443);
```
This would never bind 8443 because when the container is started the configure also calls withExposedPorts, therefore overriding the user configured values.
This means we cannot configure SSL as we need a port for HTTP and HTTPS.
For testing I simply exposed an additional port to test that this would no longer override that port - this test if tried without the code change will fail. This confirms that the code …

fix: Use addExposedPort instead of setExposedPort which overrides user configuration

---

.github/FUNDING.yml

Subj. - https://github.com/sponsors/oleg-nenashev/

Add FUNDING as I am finally able to commit more maintenance time

---

src/main/java/org/wiremock/integrations/testcontainers/WireMockContainer.java
src/test/java/org/wiremock/integrations/testcontainers/WireMockContainerRootDirTest.java
src/test/resources/__files/default-root-dir-file.json
src/test/resources/mappings/hello-default-root-dir.json
src/test/resources/org/wiremock/integrations/testcontainers/WireMockContainerRootDirTest/file.json
src/test/resources/org/wiremock/integrations/testcontainers/WireMockContainerRootDirTest/hello.json
src/test/resources/root-dir/__files/nested/root-dir-nested-file.json
src/test/resources/root-dir/__files/root-dir-file.json
src/test/resources/root-dir/mappings/hello-root-dir.json
src/test/resources/root-dir/mappings/nested/hello-nested-root-dir.json

This PR adds support for loading files and mappings from test resources directory.
By default, It will look into `src/test/resources/mappings` and `src/test/resources/__files` behaving very similarly to when `WireMockServer` is started programmatically. This path can be configured via `withRootDir(File file)`.
This addition simplifies the testing setup by providing an alternative to having to map all stub and file paths individually using `with...()` calls.
**Before:**
```
@Testcontainers
public class WireMockLoadsFileMappingsByDefaultTest {
@Container
private WireMockContainer server = new WireMockContainer("wiremock/wiremock:latest")
.withFile(new File("src/test/resources/static-file-1.txt"))
.withFile(new File("src/test/resources/static-file-2.txt"))
// other files …
```

Load files and mappings from src/test/resources by default
